module.exports = {
    testcases: [
        {
            input: [
                [
                    { type: 'apple', weight: 200 },
                    { type: 'banana', weight: 150 },
                    { type: 'apple', weight: 180 },
                    { type: 'banana', weight: 170 },
                    { type: 'mango', weight: 300 },
                ],
            ],
            expected: {
                apple: 380,
                banana: 320,
                mango: 300,
            },
        },
        {
            input: [[{ type: 'apple', weight: 200 }]],
            expected: { apple: 200 },
        },
        {
            input: [
                [
                    { type: 'apple', weight: 200 },
                    { type: 'apple', weight: 100 },
                ],
            ],
            expected: { apple: 300 },
        },
        {
            input: [
                [
                    { type: 'apple', weight: 200 },
                    { type: 'apple', weight: 100 },
                    { type: 'banana', weight: 150 },
                    { type: 'banana', weight: 170 },
                ],
            ],
            expected: { apple: 300, banana: 320 },
        },
        {
            input: [
                [
                    { type: 'apple', weight: 200 },
                    { type: 'apple', weight: 100 },
                    { type: 'banana', weight: 150 },
                ],
            ],
            expected: { apple: 300, banana: 150 },
        },
        {
            input: [
                [
                    { type: 'banana', weight: 17 },
                    { type: 'banana', weight: 281 },
                    { type: 'orange', weight: 260 },
                    { type: 'apple', weight: 237 },
                    { type: 'banana', weight: 62 },
                    { type: 'orange', weight: 131 },
                    { type: 'apple', weight: 44 },
                    { type: 'apple', weight: 293 },
                    { type: 'orange', weight: 216 },
                    { type: 'banana', weight: 265 },
                ],
            ],
            expected: { banana: 625, orange: 607, apple: 574 },
        },
        {
            input: [
                [
                    { type: 'banana', weight: 268 },
                    { type: 'orange', weight: 143 },
                    { type: 'apple', weight: 276 },
                    { type: 'orange', weight: 14 },
                    { type: 'apple', weight: 235 },
                    { type: 'apple', weight: 49 },
                    { type: 'apple', weight: 8 },
                    { type: 'apple', weight: 122 },
                    { type: 'orange', weight: 3 },
                    { type: 'banana', weight: 116 },
                ],
            ],
            expected: { banana: 384, orange: 160, apple: 690 },
        },
        {
            input: [
                [
                    { type: 'apple', weight: 175 },
                    { type: 'orange', weight: 121 },
                    { type: 'banana', weight: 91 },
                    { type: 'apple', weight: 187 },
                    { type: 'orange', weight: 206 },
                    { type: 'apple', weight: 148 },
                    { type: 'orange', weight: 196 },
                    { type: 'orange', weight: 102 },
                    { type: 'orange', weight: 45 },
                    { type: 'orange', weight: 160 },
                ],
            ],
            expected: { apple: 510, orange: 830, banana: 91 },
        },
        {
            input: [
                [
                    { type: 'orange', weight: 126 },
                    { type: 'apple', weight: 137 },
                    { type: 'banana', weight: 85 },
                    { type: 'orange', weight: 215 },
                    { type: 'banana', weight: 15 },
                    { type: 'orange', weight: 264 },
                    { type: 'banana', weight: 105 },
                    { type: 'banana', weight: 63 },
                    { type: 'apple', weight: 162 },
                    { type: 'orange', weight: 284 },
                ],
            ],
            expected: { orange: 889, apple: 299, banana: 268 },
        },
        {
            input: [
                [
                    { type: 'orange', weight: 153 },
                    { type: 'orange', weight: 152 },
                    { type: 'orange', weight: 102 },
                    { type: 'banana', weight: 191 },
                    { type: 'orange', weight: 124 },
                    { type: 'orange', weight: 39 },
                    { type: 'orange', weight: 23 },
                    { type: 'apple', weight: 87 },
                    { type: 'orange', weight: 179 },
                    { type: 'orange', weight: 261 },
                ],
            ],
            expected: { orange: 1033, banana: 191, apple: 87 },
        },
        {
            input: [
                [
                    { type: 'banana', weight: 146 },
                    { type: 'kiwi', weight: 273 },
                    { type: 'watermelon', weight: 141 },
                    { type: 'durian', weight: 120 },
                    { type: 'tomato', weight: 56 },
                    { type: 'watermelon', weight: 229 },
                    { type: 'blueberry', weight: 167 },
                    { type: 'apple', weight: 9 },
                    { type: 'durian', weight: 86 },
                    { type: 'kiwi', weight: 263 },
                    { type: 'apple', weight: 267 },
                    { type: 'blueberry', weight: 59 },
                    { type: 'apple', weight: 132 },
                    { type: 'apple', weight: 236 },
                    { type: 'banana', weight: 93 },
                ],
            ],
            expected: {
                banana: 239,
                kiwi: 536,
                watermelon: 370,
                durian: 206,
                tomato: 56,
                blueberry: 226,
                apple: 644,
            },
        },
        {
            input: [
                [
                    { type: 'apple', weight: 161 },
                    { type: 'watermelon', weight: 296 },
                    { type: 'blueberry', weight: 161 },
                    { type: 'watermelon', weight: 78 },
                    { type: 'blueberry', weight: 179 },
                    { type: 'blueberry', weight: 248 },
                    { type: 'banana', weight: 205 },
                    { type: 'apple', weight: 168 },
                    { type: 'apple', weight: 22 },
                    { type: 'apple', weight: 56 },
                    { type: 'apple', weight: 292 },
                    { type: 'durian', weight: 120 },
                    { type: 'kiwi', weight: 89 },
                    { type: 'watermelon', weight: 144 },
                    { type: 'kiwi', weight: 155 },
                ],
            ],
            expected: {
                apple: 699,
                watermelon: 518,
                blueberry: 588,
                banana: 205,
                durian: 120,
                kiwi: 244,
            },
        },
        {
            input: [
                [
                    { type: 'orange', weight: 278 },
                    { type: 'apple', weight: 62 },
                    { type: 'blueberry', weight: 103 },
                    { type: 'blueberry', weight: 28 },
                    { type: 'blueberry', weight: 93 },
                    { type: 'kiwi', weight: 161 },
                    { type: 'tomato', weight: 66 },
                    { type: 'banana', weight: 58 },
                    { type: 'watermelon', weight: 160 },
                    { type: 'durian', weight: 150 },
                    { type: 'orange', weight: 211 },
                    { type: 'watermelon', weight: 272 },
                    { type: 'durian', weight: 51 },
                    { type: 'apple', weight: 233 },
                    { type: 'banana', weight: 187 },
                ],
            ],
            expected: {
                orange: 489,
                apple: 295,
                blueberry: 224,
                kiwi: 161,
                tomato: 66,
                banana: 245,
                watermelon: 432,
                durian: 201,
            },
        },
        {
            input: [
                [
                    { type: 'blueberry', weight: 209 },
                    { type: 'banana', weight: 155 },
                    { type: 'banana', weight: 92 },
                    { type: 'watermelon', weight: 175 },
                    { type: 'orange', weight: 147 },
                    { type: 'durian', weight: 102 },
                    { type: 'orange', weight: 46 },
                    { type: 'banana', weight: 114 },
                    { type: 'kiwi', weight: 148 },
                    { type: 'watermelon', weight: 112 },
                    { type: 'banana', weight: 122 },
                    { type: 'watermelon', weight: 251 },
                    { type: 'watermelon', weight: 244 },
                    { type: 'durian', weight: 9 },
                    { type: 'tomato', weight: 94 },
                ],
            ],
            expected: {
                blueberry: 209,
                banana: 483,
                watermelon: 782,
                orange: 193,
                durian: 111,
                kiwi: 148,
                tomato: 94,
            },
        },
        {
            input: [
                [
                    { type: 'durian', weight: 294 },
                    { type: 'watermelon', weight: 75 },
                    { type: 'apple', weight: 20 },
                    { type: 'durian', weight: 242 },
                    { type: 'orange', weight: 285 },
                    { type: 'kiwi', weight: 120 },
                    { type: 'apple', weight: 5 },
                    { type: 'apple', weight: 128 },
                    { type: 'durian', weight: 176 },
                    { type: 'watermelon', weight: 281 },
                    { type: 'tomato', weight: 298 },
                    { type: 'tomato', weight: 119 },
                    { type: 'apple', weight: 266 },
                    { type: 'durian', weight: 82 },
                    { type: 'blueberry', weight: 132 },
                ],
            ],
            expected: {
                durian: 794,
                watermelon: 356,
                apple: 419,
                orange: 285,
                kiwi: 120,
                tomato: 417,
                blueberry: 132,
            },
        },
        {
            input: [
                [
                    { type: 'tomato', weight: 119 },
                    { type: 'kiwi', weight: 57 },
                    { type: 'watermelon', weight: 191 },
                    { type: 'orange', weight: 188 },
                    { type: 'orange', weight: 254 },
                    { type: 'kiwi', weight: 244 },
                    { type: 'tomato', weight: 272 },
                    { type: 'apple', weight: 145 },
                    { type: 'banana', weight: 122 },
                    { type: 'banana', weight: 273 },
                    { type: 'kiwi', weight: 211 },
                    { type: 'blueberry', weight: 187 },
                    { type: 'orange', weight: 33 },
                    { type: 'watermelon', weight: 73 },
                    { type: 'watermelon', weight: 276 },
                ],
            ],
            expected: {
                tomato: 391,
                kiwi: 512,
                watermelon: 540,
                orange: 475,
                apple: 145,
                banana: 395,
                blueberry: 187,
            },
        },
        {
            input: [
                [
                    { type: 'watermelon', weight: 299 },
                    { type: 'durian', weight: 84 },
                    { type: 'watermelon', weight: 183 },
                    { type: 'durian', weight: 236 },
                    { type: 'blueberry', weight: 185 },
                    { type: 'banana', weight: 265 },
                    { type: 'apple', weight: 131 },
                    { type: 'durian', weight: 84 },
                    { type: 'banana', weight: 8 },
                    { type: 'banana', weight: 80 },
                    { type: 'banana', weight: 28 },
                    { type: 'apple', weight: 132 },
                    { type: 'watermelon', weight: 99 },
                    { type: 'watermelon', weight: 234 },
                    { type: 'apple', weight: 235 },
                ],
            ],
            expected: {
                watermelon: 815,
                durian: 404,
                blueberry: 185,
                banana: 381,
                apple: 498,
            },
        },
        {
            input: [
                [
                    { type: 'apple', weight: 68 },
                    { type: 'kiwi', weight: 193 },
                    { type: 'orange', weight: 99 },
                    { type: 'kiwi', weight: 271 },
                    { type: 'blueberry', weight: 240 },
                    { type: 'kiwi', weight: 146 },
                    { type: 'banana', weight: 201 },
                    { type: 'tomato', weight: 227 },
                    { type: 'orange', weight: 115 },
                    { type: 'tomato', weight: 83 },
                    { type: 'durian', weight: 92 },
                    { type: 'kiwi', weight: 271 },
                    { type: 'kiwi', weight: 98 },
                    { type: 'tomato', weight: 250 },
                    { type: 'tomato', weight: 131 },
                ],
            ],
            expected: {
                apple: 68,
                kiwi: 979,
                orange: 214,
                blueberry: 240,
                banana: 201,
                tomato: 691,
                durian: 92,
            },
        },
        {
            input: [
                [
                    { type: 'blueberry', weight: 106 },
                    { type: 'blueberry', weight: 31 },
                    { type: 'watermelon', weight: 80 },
                    { type: 'orange', weight: 89 },
                    { type: 'apple', weight: 224 },
                    { type: 'orange', weight: 48 },
                    { type: 'tomato', weight: 108 },
                    { type: 'banana', weight: 237 },
                    { type: 'tomato', weight: 82 },
                    { type: 'durian', weight: 157 },
                    { type: 'apple', weight: 143 },
                    { type: 'apple', weight: 183 },
                    { type: 'kiwi', weight: 182 },
                    { type: 'tomato', weight: 153 },
                    { type: 'orange', weight: 59 },
                ],
            ],
            expected: {
                blueberry: 137,
                watermelon: 80,
                orange: 196,
                apple: 550,
                tomato: 343,
                banana: 237,
                durian: 157,
                kiwi: 182,
            },
        },
        {
            input: [
                [
                    { type: 'orange', weight: 38 },
                    { type: 'apple', weight: 263 },
                    { type: 'banana', weight: 82 },
                    { type: 'watermelon', weight: 225 },
                    { type: 'orange', weight: 194 },
                    { type: 'blueberry', weight: 3 },
                    { type: 'banana', weight: 96 },
                    { type: 'durian', weight: 86 },
                    { type: 'banana', weight: 113 },
                    { type: 'banana', weight: 82 },
                    { type: 'tomato', weight: 74 },
                    { type: 'kiwi', weight: 113 },
                    { type: 'durian', weight: 6 },
                    { type: 'tomato', weight: 245 },
                    { type: 'orange', weight: 32 },
                ],
            ],
            expected: {
                orange: 264,
                apple: 263,
                banana: 373,
                watermelon: 225,
                blueberry: 3,
                durian: 92,
                tomato: 319,
                kiwi: 113,
            },
        },
    ],
    options: {
        type: 'JSON',
    },
};
