module.exports = {
    testcases: [
        {
            input: [['sunflower', 'seed', 'tree', 'galaxy', 'cupcakes']],
            expected: { long: 2, short: 3 },
        },
        {
            input: [['Thursday']],
            expected: { long: 1, short: 0 },
        },
        {
            input: [['Friday']],
            expected: { long: 0, short: 1 },
        },
        {
            input: [['June', 'September']],
            expected: { long: 1, short: 1 },
        },
        {
            input: [
                [
                    'evdcbjui',
                    'fetlwxqrid',
                    'amnvofsikxbgc',
                    'pawzfnhlbemjc',
                    'ed',
                    'six',
                    'abilrfweyzcq',
                    'wikxb',
                    'dvkaeb',
                    'yjltasuvbho',
                ],
            ],
            expected: { long: 6, short: 4 },
        },
        {
            input: [
                [
                    'oydhqbe',
                    'nhayq',
                    'aydtsfxgq',
                    'o',
                    'macsolufxy',
                    'jrgzwmxknda',
                    'pbu',
                    'nlept',
                    'jgyiw',
                    'oavrspfbcdl',
                ],
            ],
            expected: { long: 4, short: 6 },
        },
        {
            input: [
                [
                    'wptj',
                    'akuvmgb',
                    'rzpwjmsh',
                    'urhsocamqydjl',
                    'yiphfdzjknmw',
                    'mahxfzsbydquc',
                    'qexvjahlyob',
                    'qiwgkhpbr',
                    'opq',
                    'ynjufhxeg',
                ],
            ],
            expected: { long: 7, short: 3 },
        },
        {
            input: [
                ['zihxfy', 'wchfapzkbgs', 'vha', 'negdswjtim', 'xalsior', 'gmsdc', 'mpildrhazxgk', 'aemrj', 'wn', 'ux'],
            ],
            expected: { long: 3, short: 7 },
        },
        {
            input: [
                [
                    'yailtjozhqcs',
                    'lpwsjeagrzuv',
                    'oxabvtwcde',
                    'npdrcqylshga',
                    'cwe',
                    'oaljrbhsxzcm',
                    'abvlpqmfxzy',
                    'abrwqcpj',
                    'yubznrcewotq',
                    'hfvnoqyx',
                ],
            ],
            expected: { long: 9, short: 1 },
        },
        {
            input: [['yai', 'lpwsj', 'oxabvtwcde', 'np', 'cwe', 'oalj', 'abvlp', 'abrwq', 'yu', 'hfvn']],
            expected: { long: 1, short: 9 },
        },
        {
            input: [
                [
                    'vpqxhtkoanj',
                    'abxiorf',
                    'aslu',
                    'fh',
                    'yabczxotsl',
                    'buh',
                    'fvitnpagqcz',
                    'vuh',
                    'bpyalfxjozse',
                    'abiysvketqzjf',
                ],
            ],
            expected: { long: 5, short: 5 },
        },
        {
            input: [
                [
                    'sncrvezkotyuaq',
                    'mdpvflscwyxojtrqnekubahzg',
                    'ek',
                    'agxsbhunyclmvrwpdqife',
                    'ueihlakrvqfgzow',
                    'bzouvays',
                    'hksabxfyqplmoectudizngw',
                    'jfusytlmnz',
                    'ui',
                    'wlmqkatbiscjphrgxudovyenz',
                    'agkpibwtxqcnydvhmrjzlue',
                    'dvforctyb',
                    'arbxlcdfiwmezhtygujkvqnsp',
                    'zfnrabiymtkoldgjx',
                    'xwodvcts',
                ],
            ],
            expected: { long: 13, short: 2 },
        },
        {
            input: [
                [
                    'gfarhbcizdtqekuownp',
                    'grkxmywsliqehujtfabn',
                    'qne',
                    'flabkeyqmutjxzopnchrsdg',
                    'cnvqspzmdxfw',
                    'nhdjzcrflw',
                    'jcdgwbvrsnt',
                    'qhoblakuwemx',
                    'nravybceuwihmfxjpo',
                    'dhnparjywxofvbctemsziluq',
                    'mjenpgzyc',
                    'cjidluzgxbwrhqfnvam',
                    'ecwjtymxbhl',
                    'hdwrcsfvgkptzlibmqxyajnu',
                    'xdavqnfbepuzstijhlrckm',
                ],
            ],
            expected: { long: 14, short: 1 },
        },
        {
            input: [
                [
                    'chtdmbfi',
                    'gkpebrumqfzndylaoh',
                    'sqjpiw',
                    'gcbqiskruavhjzndtpfylwom',
                    'ngta',
                    'ayodgkxtv',
                    'banixqoerlv',
                    'ucblazjsgdvwtfkexphmo',
                    'aybuepvzhocxsgqwnfjikdmrt',
                    'ohylpasmtgebficurn',
                    'apuyidwfxqtobgervnhjzckl',
                    'rfwczku',
                    'dhetvbjlw',
                    'pndqcu',
                    'afrepiqnomglskdybh',
                ],
            ],
            expected: { long: 11, short: 4 },
        },
        {
            input: [
                [
                    'xsdhp',
                    'xmibldvnoratzkqsy',
                    'xgfevidlutczm',
                    'alvufkysz',
                    'cnbrlpevyjtodhkwasf',
                    'ykdlb',
                    'zqmivgwbfanjrscx',
                    'znjvsekrmdhwfycioqa',
                    'oduprxmacjv',
                    'twuaibghxqkslpoejycf',
                    'dmox',
                    'mhrofzgplbdyqjtekvcsw',
                    'mpctfdebqayjguxih',
                    'czfxbidupyetsnhqmgrvwl',
                    'ulgtmpn',
                ],
            ],
            expected: { long: 11, short: 4 },
        },
        {
            input: [
                [
                    'neqhog',
                    'qpbaf',
                    'lnftdxeabpks',
                    'mvjohptdzlfrcbkqa',
                    'zeculqbgdavkmj',
                    'dyavihkfbruelc',
                    'ehjanmyfr',
                    'rehqtmkudaolwp',
                    'zakvgxr',
                    'auxbdrjhzpslcy',
                    'wgnxoemlvrhpudjqas',
                    'sfauwml',
                    'elrpqnaj',
                    'hzclvrwe',
                    'jnosvql',
                ],
            ],
            expected: { long: 10, short: 5 },
        },
        {
            input: [
                [
                    'tpaonldimjvghbe',
                    'hxstaeybniozwpqujmfcrdgkv',
                    'baiklhwzmjtpqeodynus',
                    'lzgdisyhnkvweptuajqbrc',
                    'rmktpvuabohy',
                    'bcpydfaiuovtwnqegzk',
                    'auwvdohnpf',
                    'lbvcwxnmiqz',
                    'phfzmworkdjvcixyqst',
                    'flqpcghibwvejzotdsakxr',
                    'deinrkxclb',
                    'ocwmvknpqzy',
                    'lymuxvsadpgbznqehwcr',
                    'faspdynjikxblzgehq',
                    'gjptzocduk',
                ],
            ],
            expected: { long: 15, short: 0 },
        },
        {
            input: [
                [
                    'mlutpwarygxk',
                    'cfnzmasp',
                    'nedtjhgkxwupzisvcbaqlfo',
                    'bzvpmfkysirgjxeuqcndhlawt',
                    'hrxwknqsjgvuiapdtzobclfem',
                    'abcizjlmkuwdev',
                    'abzmrcldteuqfojxspnyighvw',
                    'coerqvzn',
                    'fduzsrlpqytcwvkbeaijngmh',
                    'dvcylkmjighxzebrtoap',
                    'dxcuhfrnwpbeytimzq',
                    'nkvymelrw',
                    'myfhp',
                    'jaxqlnbctwsoruidyhev',
                    'krlyjmxgbahso',
                ],
            ],
            expected: { long: 14, short: 1 },
        },
        {
            input: [
                [
                    'nvscpqydkhtrboazfexgwuli',
                    'cgn',
                    'dmpgcxzeaqwhjbotsk',
                    'xnzrtd',
                    'ipfkvg',
                    'tlcd',
                    'phswxjcqoyiktm',
                    'lkservdyqignc',
                    'qi',
                    'ihlaskyxrbwpc',
                    'bvgwp',
                    'agodvwcmjk',
                    'cshvl',
                    'sydk',
                    'qyvlabwfecmrzigtxhsdokpun',
                ],
            ],
            expected: { long: 7, short: 8 },
        },
        {
            input: [
                [
                    'gaw',
                    'izotxwcsbl',
                    'ifaob',
                    'ombacdrpeyhn',
                    'dltqrwfzgky',
                    'vhpjeiqdxtcbgnumolsza',
                    'rscnhvmbezikjglqyuadop',
                    'lnrabixjm',
                    'abomcx',
                    'chptvxywefsbdnzmqaj',
                    'nabrcu',
                    'apbkj',
                    'tdzecvghpbqywsnomilfr',
                    'pnrqeuyzb',
                    'yxevshjtgwcfdb',
                ],
            ],
            expected: { long: 10, short: 5 },
        },
    ],
    options: {
        type: 'JSON',
    },
};
