module.exports = {
    testcases: [
        { input: [1, 1], expected: 'C-tier Fruit' },
        { input: [9, 1999], expected: 'C-tier Fruit' },
        { input: [10, 1999], expected: 'C-tier Fruit' },
        { input: [9, 2000], expected: 'C-tier Fruit' },
        { input: [10, 2000], expected: 'B-tier Fruit' },
        { input: [10, 8000], expected: 'B-tier Fruit' },
        { input: [15, 8000], expected: 'B-tier Fruit' },
        { input: [15, 2000], expected: 'B-tier Fruit' },
        { input: [16, 2000], expected: 'B-tier Fruit' },
        { input: [16, 1999], expected: 'B-tier Fruit' },
        { input: [15, 8001], expected: 'B-tier Fruit' },
        { input: [9, 8001], expected: 'B-tier Fruit' },
        { input: [16, 8001], expected: 'A-tier Fruit' },
        { input: [20, 9999], expected: 'A-tier Fruit' },
        { input: [1, 2759], expected: 'C-tier Fruit' },
        { input: [2, 4630], expected: 'C-tier Fruit' },
        { input: [1, 9340], expected: 'B-tier Fruit' },
        { input: [3, 9718], expected: 'B-tier Fruit' },
        { input: [18, 8067], expected: 'A-tier Fruit' },
        { input: [7, 9151], expected: 'B-tier Fruit' },
        { input: [20, 8965], expected: 'A-tier Fruit' },
        { input: [20, 5424], expected: 'B-tier Fruit' },
        { input: [17, 7064], expected: 'B-tier Fruit' },
        { input: [8, 9000], expected: 'B-tier Fruit' },
        { input: [16, 9009], expected: 'A-tier Fruit' },
    ],

    options: {},
};
