module.exports = {
    testcases: [
        {
            input: [[{ score: 98 }, { score: 66 }, { score: 82 }]],
            expected: [
                { score: 98, comment: 'distinction' },
                { score: 66, comment: 'pass' },
                { score: 82, comment: 'distinction' },
            ],
        },
        {
            input: [[{ score: 0 }]],
            expected: [{ score: 0, comment: 'poor' }],
        },
        {
            input: [[{ score: 60 }]],
            expected: [{ score: 60, comment: 'pass' }],
        },
        {
            input: [[{ score: 100 }]],
            expected: [{ score: 100, comment: 'distinction' }],
        },
        {
            input: [[{ score: 40 }, { score: 74 }]],
            expected: [
                { score: 40, comment: 'poor' },
                { score: 74, comment: 'pass' },
            ],
        },
        {
            input: [[{ score: 60 }, { score: 76 }]],
            expected: [
                { score: 60, comment: 'pass' },
                { score: 76, comment: 'distinction' },
            ],
        },
        {
            input: [[{ score: 100 }, { score: 49 }, { score: 73 }]],
            expected: [
                { score: 100, comment: 'distinction' },
                { score: 49, comment: 'poor' },
                { score: 73, comment: 'pass' },
            ],
        },
        {
            input: [[{ score: 100 }, { score: 63 }, { score: 38 }, { score: 52 }, { score: 99 }]],
            expected: [
                { score: 100, comment: 'distinction' },
                { score: 63, comment: 'pass' },
                { score: 38, comment: 'poor' },
                { score: 52, comment: 'pass' },
                { score: 99, comment: 'distinction' },
            ],
        },
        {
            input: [[{ score: 12 }, { score: 77 }, { score: 74 }, { score: 47 }, { score: 81 }]],
            expected: [
                { score: 12, comment: 'poor' },
                { score: 77, comment: 'distinction' },
                { score: 74, comment: 'pass' },
                { score: 47, comment: 'poor' },
                { score: 81, comment: 'distinction' },
            ],
        },
        {
            input: [[{ score: 91 }, { score: 85 }, { score: 97 }, { score: 74 }, { score: 63 }]],
            expected: [
                { score: 91, comment: 'distinction' },
                { score: 85, comment: 'distinction' },
                { score: 97, comment: 'distinction' },
                { score: 74, comment: 'pass' },
                { score: 63, comment: 'pass' },
            ],
        },
        {
            input: [
                [
                    { score: 89 },
                    { score: 33 },
                    { score: 41 },
                    { score: 52 },
                    { score: 100 },
                    { score: 48 },
                    { score: 86 },
                    { score: 12 },
                    { score: 64 },
                    { score: 87 },
                    { score: 82 },
                    { score: 20 },
                    { score: 98 },
                    { score: 13 },
                    { score: 49 },
                    { score: 71 },
                    { score: 89 },
                    { score: 39 },
                    { score: 67 },
                    { score: 10 },
                    { score: 71 },
                    { score: 60 },
                    { score: 42 },
                    { score: 97 },
                    { score: 7 },
                    { score: 47 },
                    { score: 18 },
                    { score: 71 },
                    { score: 80 },
                    { score: 54 },
                    { score: 31 },
                    { score: 8 },
                    { score: 32 },
                    { score: 50 },
                    { score: 85 },
                    { score: 65 },
                    { score: 48 },
                    { score: 30 },
                    { score: 41 },
                    { score: 34 },
                    { score: 36 },
                    { score: 52 },
                    { score: 73 },
                    { score: 29 },
                    { score: 20 },
                    { score: 36 },
                    { score: 59 },
                    { score: 38 },
                    { score: 84 },
                    { score: 32 },
                    { score: 42 },
                    { score: 32 },
                    { score: 16 },
                    { score: 67 },
                    { score: 73 },
                    { score: 29 },
                    { score: 47 },
                    { score: 53 },
                    { score: 65 },
                    { score: 63 },
                    { score: 60 },
                    { score: 21 },
                    { score: 62 },
                    { score: 64 },
                    { score: 62 },
                    { score: 72 },
                ],
            ],
            expected: [
                { score: 89, comment: 'distinction' },
                { score: 33, comment: 'poor' },
                { score: 41, comment: 'poor' },
                { score: 52, comment: 'pass' },
                { score: 100, comment: 'distinction' },
                { score: 48, comment: 'poor' },
                { score: 86, comment: 'distinction' },
                { score: 12, comment: 'poor' },
                { score: 64, comment: 'pass' },
                { score: 87, comment: 'distinction' },
                { score: 82, comment: 'distinction' },
                { score: 20, comment: 'poor' },
                { score: 98, comment: 'distinction' },
                { score: 13, comment: 'poor' },
                { score: 49, comment: 'poor' },
                { score: 71, comment: 'pass' },
                { score: 89, comment: 'distinction' },
                { score: 39, comment: 'poor' },
                { score: 67, comment: 'pass' },
                { score: 10, comment: 'poor' },
                { score: 71, comment: 'pass' },
                { score: 60, comment: 'pass' },
                { score: 42, comment: 'poor' },
                { score: 97, comment: 'distinction' },
                { score: 7, comment: 'poor' },
                { score: 47, comment: 'poor' },
                { score: 18, comment: 'poor' },
                { score: 71, comment: 'pass' },
                { score: 80, comment: 'distinction' },
                { score: 54, comment: 'pass' },
                { score: 31, comment: 'poor' },
                { score: 8, comment: 'poor' },
                { score: 32, comment: 'poor' },
                { score: 50, comment: 'pass' },
                { score: 85, comment: 'distinction' },
                { score: 65, comment: 'pass' },
                { score: 48, comment: 'poor' },
                { score: 30, comment: 'poor' },
                { score: 41, comment: 'poor' },
                { score: 34, comment: 'poor' },
                { score: 36, comment: 'poor' },
                { score: 52, comment: 'pass' },
                { score: 73, comment: 'pass' },
                { score: 29, comment: 'poor' },
                { score: 20, comment: 'poor' },
                { score: 36, comment: 'poor' },
                { score: 59, comment: 'pass' },
                { score: 38, comment: 'poor' },
                { score: 84, comment: 'distinction' },
                { score: 32, comment: 'poor' },
                { score: 42, comment: 'poor' },
                { score: 32, comment: 'poor' },
                { score: 16, comment: 'poor' },
                { score: 67, comment: 'pass' },
                { score: 73, comment: 'pass' },
                { score: 29, comment: 'poor' },
                { score: 47, comment: 'poor' },
                { score: 53, comment: 'pass' },
                { score: 65, comment: 'pass' },
                { score: 63, comment: 'pass' },
                { score: 60, comment: 'pass' },
                { score: 21, comment: 'poor' },
                { score: 62, comment: 'pass' },
                { score: 64, comment: 'pass' },
                { score: 62, comment: 'pass' },
                { score: 72, comment: 'pass' },
            ],
        },
        {
            input: [
                [
                    { score: 67 },
                    { score: 71 },
                    { score: 47 },
                    { score: 20 },
                    { score: 12 },
                    { score: 68 },
                    { score: 96 },
                    { score: 9 },
                    { score: 70 },
                    { score: 40 },
                    { score: 47 },
                    { score: 10 },
                    { score: 50 },
                    { score: 5 },
                    { score: 99 },
                    { score: 22 },
                    { score: 88 },
                    { score: 72 },
                    { score: 24 },
                    { score: 62 },
                    { score: 83 },
                    { score: 19 },
                    { score: 26 },
                    { score: 73 },
                    { score: 57 },
                    { score: 65 },
                    { score: 68 },
                    { score: 29 },
                    { score: 38 },
                    { score: 84 },
                    { score: 2 },
                    { score: 33 },
                    { score: 74 },
                    { score: 97 },
                    { score: 35 },
                    { score: 61 },
                    { score: 62 },
                    { score: 42 },
                    { score: 15 },
                    { score: 4 },
                    { score: 53 },
                    { score: 30 },
                    { score: 77 },
                    { score: 65 },
                    { score: 86 },
                    { score: 43 },
                ],
            ],
            expected: [
                { score: 67, comment: 'pass' },
                { score: 71, comment: 'pass' },
                { score: 47, comment: 'poor' },
                { score: 20, comment: 'poor' },
                { score: 12, comment: 'poor' },
                { score: 68, comment: 'pass' },
                { score: 96, comment: 'distinction' },
                { score: 9, comment: 'poor' },
                { score: 70, comment: 'pass' },
                { score: 40, comment: 'poor' },
                { score: 47, comment: 'poor' },
                { score: 10, comment: 'poor' },
                { score: 50, comment: 'pass' },
                { score: 5, comment: 'poor' },
                { score: 99, comment: 'distinction' },
                { score: 22, comment: 'poor' },
                { score: 88, comment: 'distinction' },
                { score: 72, comment: 'pass' },
                { score: 24, comment: 'poor' },
                { score: 62, comment: 'pass' },
                { score: 83, comment: 'distinction' },
                { score: 19, comment: 'poor' },
                { score: 26, comment: 'poor' },
                { score: 73, comment: 'pass' },
                { score: 57, comment: 'pass' },
                { score: 65, comment: 'pass' },
                { score: 68, comment: 'pass' },
                { score: 29, comment: 'poor' },
                { score: 38, comment: 'poor' },
                { score: 84, comment: 'distinction' },
                { score: 2, comment: 'poor' },
                { score: 33, comment: 'poor' },
                { score: 74, comment: 'pass' },
                { score: 97, comment: 'distinction' },
                { score: 35, comment: 'poor' },
                { score: 61, comment: 'pass' },
                { score: 62, comment: 'pass' },
                { score: 42, comment: 'poor' },
                { score: 15, comment: 'poor' },
                { score: 4, comment: 'poor' },
                { score: 53, comment: 'pass' },
                { score: 30, comment: 'poor' },
                { score: 77, comment: 'distinction' },
                { score: 65, comment: 'pass' },
                { score: 86, comment: 'distinction' },
                { score: 43, comment: 'poor' },
            ],
        },
        {
            input: [
                [
                    { score: 80 },
                    { score: 37 },
                    { score: 57 },
                    { score: 69 },
                    { score: 87 },
                    { score: 97 },
                    { score: 27 },
                    { score: 11 },
                    { score: 99 },
                    { score: 34 },
                    { score: 82 },
                    { score: 31 },
                    { score: 15 },
                    { score: 69 },
                    { score: 82 },
                    { score: 2 },
                    { score: 37 },
                    { score: 83 },
                    { score: 71 },
                    { score: 84 },
                    { score: 68 },
                    { score: 11 },
                    { score: 21 },
                    { score: 91 },
                    { score: 20 },
                    { score: 11 },
                    { score: 22 },
                    { score: 4 },
                    { score: 64 },
                    { score: 100 },
                    { score: 26 },
                    { score: 61 },
                    { score: 56 },
                    { score: 34 },
                ],
            ],
            expected: [
                { score: 80, comment: 'distinction' },
                { score: 37, comment: 'poor' },
                { score: 57, comment: 'pass' },
                { score: 69, comment: 'pass' },
                { score: 87, comment: 'distinction' },
                { score: 97, comment: 'distinction' },
                { score: 27, comment: 'poor' },
                { score: 11, comment: 'poor' },
                { score: 99, comment: 'distinction' },
                { score: 34, comment: 'poor' },
                { score: 82, comment: 'distinction' },
                { score: 31, comment: 'poor' },
                { score: 15, comment: 'poor' },
                { score: 69, comment: 'pass' },
                { score: 82, comment: 'distinction' },
                { score: 2, comment: 'poor' },
                { score: 37, comment: 'poor' },
                { score: 83, comment: 'distinction' },
                { score: 71, comment: 'pass' },
                { score: 84, comment: 'distinction' },
                { score: 68, comment: 'pass' },
                { score: 11, comment: 'poor' },
                { score: 21, comment: 'poor' },
                { score: 91, comment: 'distinction' },
                { score: 20, comment: 'poor' },
                { score: 11, comment: 'poor' },
                { score: 22, comment: 'poor' },
                { score: 4, comment: 'poor' },
                { score: 64, comment: 'pass' },
                { score: 100, comment: 'distinction' },
                { score: 26, comment: 'poor' },
                { score: 61, comment: 'pass' },
                { score: 56, comment: 'pass' },
                { score: 34, comment: 'poor' },
            ],
        },
        {
            input: [
                [
                    { score: 2 },
                    { score: 37 },
                    { score: 17 },
                    { score: 23 },
                    { score: 43 },
                    { score: 93 },
                    { score: 73 },
                    { score: 77 },
                    { score: 2 },
                    { score: 71 },
                    { score: 94 },
                    { score: 10 },
                    { score: 64 },
                    { score: 20 },
                    { score: 63 },
                    { score: 63 },
                    { score: 70 },
                    { score: 25 },
                    { score: 32 },
                    { score: 7 },
                    { score: 40 },
                    { score: 44 },
                    { score: 48 },
                    { score: 9 },
                    { score: 67 },
                    { score: 78 },
                    { score: 59 },
                    { score: 100 },
                    { score: 80 },
                    { score: 60 },
                    { score: 20 },
                    { score: 93 },
                    { score: 6 },
                    { score: 78 },
                    { score: 32 },
                    { score: 6 },
                    { score: 48 },
                    { score: 72 },
                    { score: 25 },
                    { score: 25 },
                    { score: 7 },
                    { score: 45 },
                    { score: 92 },
                    { score: 6 },
                    { score: 79 },
                    { score: 79 },
                    { score: 93 },
                    { score: 11 },
                    { score: 98 },
                    { score: 85 },
                    { score: 95 },
                ],
            ],
            expected: [
                { score: 2, comment: 'poor' },
                { score: 37, comment: 'poor' },
                { score: 17, comment: 'poor' },
                { score: 23, comment: 'poor' },
                { score: 43, comment: 'poor' },
                { score: 93, comment: 'distinction' },
                { score: 73, comment: 'pass' },
                { score: 77, comment: 'distinction' },
                { score: 2, comment: 'poor' },
                { score: 71, comment: 'pass' },
                { score: 94, comment: 'distinction' },
                { score: 10, comment: 'poor' },
                { score: 64, comment: 'pass' },
                { score: 20, comment: 'poor' },
                { score: 63, comment: 'pass' },
                { score: 63, comment: 'pass' },
                { score: 70, comment: 'pass' },
                { score: 25, comment: 'poor' },
                { score: 32, comment: 'poor' },
                { score: 7, comment: 'poor' },
                { score: 40, comment: 'poor' },
                { score: 44, comment: 'poor' },
                { score: 48, comment: 'poor' },
                { score: 9, comment: 'poor' },
                { score: 67, comment: 'pass' },
                { score: 78, comment: 'distinction' },
                { score: 59, comment: 'pass' },
                { score: 100, comment: 'distinction' },
                { score: 80, comment: 'distinction' },
                { score: 60, comment: 'pass' },
                { score: 20, comment: 'poor' },
                { score: 93, comment: 'distinction' },
                { score: 6, comment: 'poor' },
                { score: 78, comment: 'distinction' },
                { score: 32, comment: 'poor' },
                { score: 6, comment: 'poor' },
                { score: 48, comment: 'poor' },
                { score: 72, comment: 'pass' },
                { score: 25, comment: 'poor' },
                { score: 25, comment: 'poor' },
                { score: 7, comment: 'poor' },
                { score: 45, comment: 'poor' },
                { score: 92, comment: 'distinction' },
                { score: 6, comment: 'poor' },
                { score: 79, comment: 'distinction' },
                { score: 79, comment: 'distinction' },
                { score: 93, comment: 'distinction' },
                { score: 11, comment: 'poor' },
                { score: 98, comment: 'distinction' },
                { score: 85, comment: 'distinction' },
                { score: 95, comment: 'distinction' },
            ],
        },
        {
            input: [
                [
                    { score: 92 },
                    { score: 17 },
                    { score: 34 },
                    { score: 16 },
                    { score: 53 },
                    { score: 41 },
                    { score: 79 },
                    { score: 30 },
                    { score: 87 },
                    { score: 47 },
                    { score: 72 },
                    { score: 81 },
                    { score: 41 },
                    { score: 74 },
                    { score: 27 },
                    { score: 67 },
                    { score: 74 },
                    { score: 51 },
                    { score: 94 },
                    { score: 40 },
                    { score: 69 },
                    { score: 69 },
                    { score: 53 },
                    { score: 72 },
                    { score: 78 },
                    { score: 74 },
                    { score: 21 },
                    { score: 68 },
                    { score: 17 },
                    { score: 100 },
                    { score: 73 },
                    { score: 92 },
                    { score: 11 },
                    { score: 84 },
                    { score: 63 },
                    { score: 79 },
                    { score: 8 },
                    { score: 42 },
                ],
            ],
            expected: [
                { score: 92, comment: 'distinction' },
                { score: 17, comment: 'poor' },
                { score: 34, comment: 'poor' },
                { score: 16, comment: 'poor' },
                { score: 53, comment: 'pass' },
                { score: 41, comment: 'poor' },
                { score: 79, comment: 'distinction' },
                { score: 30, comment: 'poor' },
                { score: 87, comment: 'distinction' },
                { score: 47, comment: 'poor' },
                { score: 72, comment: 'pass' },
                { score: 81, comment: 'distinction' },
                { score: 41, comment: 'poor' },
                { score: 74, comment: 'pass' },
                { score: 27, comment: 'poor' },
                { score: 67, comment: 'pass' },
                { score: 74, comment: 'pass' },
                { score: 51, comment: 'pass' },
                { score: 94, comment: 'distinction' },
                { score: 40, comment: 'poor' },
                { score: 69, comment: 'pass' },
                { score: 69, comment: 'pass' },
                { score: 53, comment: 'pass' },
                { score: 72, comment: 'pass' },
                { score: 78, comment: 'distinction' },
                { score: 74, comment: 'pass' },
                { score: 21, comment: 'poor' },
                { score: 68, comment: 'pass' },
                { score: 17, comment: 'poor' },
                { score: 100, comment: 'distinction' },
                { score: 73, comment: 'pass' },
                { score: 92, comment: 'distinction' },
                { score: 11, comment: 'poor' },
                { score: 84, comment: 'distinction' },
                { score: 63, comment: 'pass' },
                { score: 79, comment: 'distinction' },
                { score: 8, comment: 'poor' },
                { score: 42, comment: 'poor' },
            ],
        },
        {
            input: [
                [
                    { score: 63 },
                    { score: 16 },
                    { score: 34 },
                    { score: 34 },
                    { score: 65 },
                    { score: 28 },
                    { score: 48 },
                    { score: 15 },
                    { score: 74 },
                    { score: 7 },
                    { score: 72 },
                    { score: 8 },
                    { score: 19 },
                    { score: 45 },
                    { score: 25 },
                    { score: 49 },
                    { score: 59 },
                    { score: 60 },
                    { score: 58 },
                    { score: 18 },
                    { score: 52 },
                    { score: 71 },
                    { score: 25 },
                    { score: 53 },
                    { score: 64 },
                    { score: 64 },
                    { score: 8 },
                    { score: 97 },
                    { score: 1 },
                    { score: 51 },
                    { score: 11 },
                    { score: 92 },
                    { score: 77 },
                    { score: 41 },
                    { score: 92 },
                    { score: 24 },
                    { score: 19 },
                    { score: 39 },
                    { score: 29 },
                    { score: 33 },
                    { score: 13 },
                    { score: 34 },
                    { score: 51 },
                    { score: 89 },
                    { score: 30 },
                    { score: 45 },
                    { score: 49 },
                    { score: 40 },
                    { score: 46 },
                    { score: 92 },
                    { score: 0 },
                    { score: 27 },
                    { score: 65 },
                    { score: 16 },
                    { score: 79 },
                    { score: 11 },
                ],
            ],
            expected: [
                { score: 63, comment: 'pass' },
                { score: 16, comment: 'poor' },
                { score: 34, comment: 'poor' },
                { score: 34, comment: 'poor' },
                { score: 65, comment: 'pass' },
                { score: 28, comment: 'poor' },
                { score: 48, comment: 'poor' },
                { score: 15, comment: 'poor' },
                { score: 74, comment: 'pass' },
                { score: 7, comment: 'poor' },
                { score: 72, comment: 'pass' },
                { score: 8, comment: 'poor' },
                { score: 19, comment: 'poor' },
                { score: 45, comment: 'poor' },
                { score: 25, comment: 'poor' },
                { score: 49, comment: 'poor' },
                { score: 59, comment: 'pass' },
                { score: 60, comment: 'pass' },
                { score: 58, comment: 'pass' },
                { score: 18, comment: 'poor' },
                { score: 52, comment: 'pass' },
                { score: 71, comment: 'pass' },
                { score: 25, comment: 'poor' },
                { score: 53, comment: 'pass' },
                { score: 64, comment: 'pass' },
                { score: 64, comment: 'pass' },
                { score: 8, comment: 'poor' },
                { score: 97, comment: 'distinction' },
                { score: 1, comment: 'poor' },
                { score: 51, comment: 'pass' },
                { score: 11, comment: 'poor' },
                { score: 92, comment: 'distinction' },
                { score: 77, comment: 'distinction' },
                { score: 41, comment: 'poor' },
                { score: 92, comment: 'distinction' },
                { score: 24, comment: 'poor' },
                { score: 19, comment: 'poor' },
                { score: 39, comment: 'poor' },
                { score: 29, comment: 'poor' },
                { score: 33, comment: 'poor' },
                { score: 13, comment: 'poor' },
                { score: 34, comment: 'poor' },
                { score: 51, comment: 'pass' },
                { score: 89, comment: 'distinction' },
                { score: 30, comment: 'poor' },
                { score: 45, comment: 'poor' },
                { score: 49, comment: 'poor' },
                { score: 40, comment: 'poor' },
                { score: 46, comment: 'poor' },
                { score: 92, comment: 'distinction' },
                { score: 0, comment: 'poor' },
                { score: 27, comment: 'poor' },
                { score: 65, comment: 'pass' },
                { score: 16, comment: 'poor' },
                { score: 79, comment: 'distinction' },
                { score: 11, comment: 'poor' },
            ],
        },
        {
            input: [
                [
                    { score: 34 },
                    { score: 2 },
                    { score: 13 },
                    { score: 36 },
                    { score: 84 },
                    { score: 47 },
                    { score: 56 },
                    { score: 17 },
                    { score: 99 },
                    { score: 65 },
                    { score: 7 },
                    { score: 69 },
                    { score: 96 },
                    { score: 77 },
                    { score: 2 },
                    { score: 50 },
                    { score: 22 },
                    { score: 6 },
                    { score: 33 },
                    { score: 96 },
                    { score: 21 },
                    { score: 25 },
                    { score: 50 },
                    { score: 40 },
                    { score: 88 },
                    { score: 98 },
                    { score: 3 },
                    { score: 70 },
                    { score: 76 },
                    { score: 25 },
                    { score: 56 },
                    { score: 66 },
                    { score: 21 },
                    { score: 26 },
                    { score: 29 },
                    { score: 16 },
                    { score: 78 },
                ],
            ],
            expected: [
                { score: 34, comment: 'poor' },
                { score: 2, comment: 'poor' },
                { score: 13, comment: 'poor' },
                { score: 36, comment: 'poor' },
                { score: 84, comment: 'distinction' },
                { score: 47, comment: 'poor' },
                { score: 56, comment: 'pass' },
                { score: 17, comment: 'poor' },
                { score: 99, comment: 'distinction' },
                { score: 65, comment: 'pass' },
                { score: 7, comment: 'poor' },
                { score: 69, comment: 'pass' },
                { score: 96, comment: 'distinction' },
                { score: 77, comment: 'distinction' },
                { score: 2, comment: 'poor' },
                { score: 50, comment: 'pass' },
                { score: 22, comment: 'poor' },
                { score: 6, comment: 'poor' },
                { score: 33, comment: 'poor' },
                { score: 96, comment: 'distinction' },
                { score: 21, comment: 'poor' },
                { score: 25, comment: 'poor' },
                { score: 50, comment: 'pass' },
                { score: 40, comment: 'poor' },
                { score: 88, comment: 'distinction' },
                { score: 98, comment: 'distinction' },
                { score: 3, comment: 'poor' },
                { score: 70, comment: 'pass' },
                { score: 76, comment: 'distinction' },
                { score: 25, comment: 'poor' },
                { score: 56, comment: 'pass' },
                { score: 66, comment: 'pass' },
                { score: 21, comment: 'poor' },
                { score: 26, comment: 'poor' },
                { score: 29, comment: 'poor' },
                { score: 16, comment: 'poor' },
                { score: 78, comment: 'distinction' },
            ],
        },
        {
            input: [
                [
                    { score: 57 },
                    { score: 25 },
                    { score: 64 },
                    { score: 62 },
                    { score: 32 },
                    { score: 57 },
                    { score: 46 },
                    { score: 20 },
                    { score: 81 },
                    { score: 48 },
                    { score: 14 },
                    { score: 98 },
                    { score: 59 },
                    { score: 61 },
                    { score: 44 },
                    { score: 22 },
                    { score: 28 },
                    { score: 46 },
                    { score: 68 },
                    { score: 9 },
                    { score: 61 },
                    { score: 78 },
                    { score: 87 },
                    { score: 32 },
                    { score: 18 },
                    { score: 32 },
                    { score: 75 },
                    { score: 55 },
                    { score: 29 },
                    { score: 48 },
                    { score: 13 },
                    { score: 81 },
                    { score: 12 },
                    { score: 68 },
                    { score: 20 },
                    { score: 100 },
                    { score: 69 },
                    { score: 43 },
                    { score: 8 },
                    { score: 54 },
                    { score: 80 },
                    { score: 66 },
                    { score: 12 },
                    { score: 98 },
                    { score: 59 },
                    { score: 89 },
                    { score: 88 },
                    { score: 91 },
                    { score: 51 },
                    { score: 60 },
                    { score: 18 },
                    { score: 65 },
                ],
            ],
            expected: [
                { score: 57, comment: 'pass' },
                { score: 25, comment: 'poor' },
                { score: 64, comment: 'pass' },
                { score: 62, comment: 'pass' },
                { score: 32, comment: 'poor' },
                { score: 57, comment: 'pass' },
                { score: 46, comment: 'poor' },
                { score: 20, comment: 'poor' },
                { score: 81, comment: 'distinction' },
                { score: 48, comment: 'poor' },
                { score: 14, comment: 'poor' },
                { score: 98, comment: 'distinction' },
                { score: 59, comment: 'pass' },
                { score: 61, comment: 'pass' },
                { score: 44, comment: 'poor' },
                { score: 22, comment: 'poor' },
                { score: 28, comment: 'poor' },
                { score: 46, comment: 'poor' },
                { score: 68, comment: 'pass' },
                { score: 9, comment: 'poor' },
                { score: 61, comment: 'pass' },
                { score: 78, comment: 'distinction' },
                { score: 87, comment: 'distinction' },
                { score: 32, comment: 'poor' },
                { score: 18, comment: 'poor' },
                { score: 32, comment: 'poor' },
                { score: 75, comment: 'distinction' },
                { score: 55, comment: 'pass' },
                { score: 29, comment: 'poor' },
                { score: 48, comment: 'poor' },
                { score: 13, comment: 'poor' },
                { score: 81, comment: 'distinction' },
                { score: 12, comment: 'poor' },
                { score: 68, comment: 'pass' },
                { score: 20, comment: 'poor' },
                { score: 100, comment: 'distinction' },
                { score: 69, comment: 'pass' },
                { score: 43, comment: 'poor' },
                { score: 8, comment: 'poor' },
                { score: 54, comment: 'pass' },
                { score: 80, comment: 'distinction' },
                { score: 66, comment: 'pass' },
                { score: 12, comment: 'poor' },
                { score: 98, comment: 'distinction' },
                { score: 59, comment: 'pass' },
                { score: 89, comment: 'distinction' },
                { score: 88, comment: 'distinction' },
                { score: 91, comment: 'distinction' },
                { score: 51, comment: 'pass' },
                { score: 60, comment: 'pass' },
                { score: 18, comment: 'poor' },
                { score: 65, comment: 'pass' },
            ],
        },
        {
            input: [
                [
                    { score: 44 },
                    { score: 64 },
                    { score: 1 },
                    { score: 34 },
                    { score: 75 },
                    { score: 49 },
                    { score: 73 },
                    { score: 37 },
                    { score: 96 },
                    { score: 47 },
                    { score: 8 },
                    { score: 91 },
                    { score: 79 },
                    { score: 66 },
                    { score: 46 },
                    { score: 63 },
                    { score: 96 },
                    { score: 3 },
                    { score: 25 },
                    { score: 39 },
                    { score: 57 },
                    { score: 84 },
                    { score: 6 },
                    { score: 84 },
                    { score: 14 },
                    { score: 41 },
                    { score: 49 },
                    { score: 61 },
                    { score: 64 },
                    { score: 34 },
                    { score: 65 },
                    { score: 0 },
                    { score: 42 },
                    { score: 84 },
                    { score: 52 },
                    { score: 20 },
                    { score: 45 },
                    { score: 76 },
                    { score: 70 },
                    { score: 76 },
                    { score: 86 },
                    { score: 24 },
                    { score: 17 },
                    { score: 3 },
                    { score: 0 },
                    { score: 12 },
                    { score: 44 },
                    { score: 70 },
                    { score: 75 },
                    { score: 69 },
                    { score: 85 },
                    { score: 18 },
                    { score: 71 },
                    { score: 92 },
                    { score: 8 },
                    { score: 31 },
                    { score: 22 },
                    { score: 81 },
                    { score: 44 },
                    { score: 38 },
                    { score: 97 },
                ],
            ],
            expected: [
                { score: 44, comment: 'poor' },
                { score: 64, comment: 'pass' },
                { score: 1, comment: 'poor' },
                { score: 34, comment: 'poor' },
                { score: 75, comment: 'distinction' },
                { score: 49, comment: 'poor' },
                { score: 73, comment: 'pass' },
                { score: 37, comment: 'poor' },
                { score: 96, comment: 'distinction' },
                { score: 47, comment: 'poor' },
                { score: 8, comment: 'poor' },
                { score: 91, comment: 'distinction' },
                { score: 79, comment: 'distinction' },
                { score: 66, comment: 'pass' },
                { score: 46, comment: 'poor' },
                { score: 63, comment: 'pass' },
                { score: 96, comment: 'distinction' },
                { score: 3, comment: 'poor' },
                { score: 25, comment: 'poor' },
                { score: 39, comment: 'poor' },
                { score: 57, comment: 'pass' },
                { score: 84, comment: 'distinction' },
                { score: 6, comment: 'poor' },
                { score: 84, comment: 'distinction' },
                { score: 14, comment: 'poor' },
                { score: 41, comment: 'poor' },
                { score: 49, comment: 'poor' },
                { score: 61, comment: 'pass' },
                { score: 64, comment: 'pass' },
                { score: 34, comment: 'poor' },
                { score: 65, comment: 'pass' },
                { score: 0, comment: 'poor' },
                { score: 42, comment: 'poor' },
                { score: 84, comment: 'distinction' },
                { score: 52, comment: 'pass' },
                { score: 20, comment: 'poor' },
                { score: 45, comment: 'poor' },
                { score: 76, comment: 'distinction' },
                { score: 70, comment: 'pass' },
                { score: 76, comment: 'distinction' },
                { score: 86, comment: 'distinction' },
                { score: 24, comment: 'poor' },
                { score: 17, comment: 'poor' },
                { score: 3, comment: 'poor' },
                { score: 0, comment: 'poor' },
                { score: 12, comment: 'poor' },
                { score: 44, comment: 'poor' },
                { score: 70, comment: 'pass' },
                { score: 75, comment: 'distinction' },
                { score: 69, comment: 'pass' },
                { score: 85, comment: 'distinction' },
                { score: 18, comment: 'poor' },
                { score: 71, comment: 'pass' },
                { score: 92, comment: 'distinction' },
                { score: 8, comment: 'poor' },
                { score: 31, comment: 'poor' },
                { score: 22, comment: 'poor' },
                { score: 81, comment: 'distinction' },
                { score: 44, comment: 'poor' },
                { score: 38, comment: 'poor' },
                { score: 97, comment: 'distinction' },
            ],
        },
        {
            input: [
                [
                    { score: 86 },
                    { score: 92 },
                    { score: 81 },
                    { score: 51 },
                    { score: 66 },
                    { score: 68 },
                    { score: 44 },
                    { score: 61 },
                    { score: 76 },
                    { score: 7 },
                    { score: 6 },
                    { score: 37 },
                    { score: 69 },
                    { score: 66 },
                    { score: 29 },
                    { score: 59 },
                    { score: 78 },
                    { score: 97 },
                    { score: 57 },
                    { score: 49 },
                    { score: 36 },
                    { score: 82 },
                    { score: 30 },
                    { score: 43 },
                    { score: 62 },
                    { score: 13 },
                    { score: 54 },
                    { score: 28 },
                    { score: 67 },
                    { score: 4 },
                    { score: 5 },
                    { score: 48 },
                    { score: 20 },
                    { score: 27 },
                    { score: 76 },
                    { score: 36 },
                    { score: 71 },
                ],
            ],
            expected: [
                { score: 86, comment: 'distinction' },
                { score: 92, comment: 'distinction' },
                { score: 81, comment: 'distinction' },
                { score: 51, comment: 'pass' },
                { score: 66, comment: 'pass' },
                { score: 68, comment: 'pass' },
                { score: 44, comment: 'poor' },
                { score: 61, comment: 'pass' },
                { score: 76, comment: 'distinction' },
                { score: 7, comment: 'poor' },
                { score: 6, comment: 'poor' },
                { score: 37, comment: 'poor' },
                { score: 69, comment: 'pass' },
                { score: 66, comment: 'pass' },
                { score: 29, comment: 'poor' },
                { score: 59, comment: 'pass' },
                { score: 78, comment: 'distinction' },
                { score: 97, comment: 'distinction' },
                { score: 57, comment: 'pass' },
                { score: 49, comment: 'poor' },
                { score: 36, comment: 'poor' },
                { score: 82, comment: 'distinction' },
                { score: 30, comment: 'poor' },
                { score: 43, comment: 'poor' },
                { score: 62, comment: 'pass' },
                { score: 13, comment: 'poor' },
                { score: 54, comment: 'pass' },
                { score: 28, comment: 'poor' },
                { score: 67, comment: 'pass' },
                { score: 4, comment: 'poor' },
                { score: 5, comment: 'poor' },
                { score: 48, comment: 'poor' },
                { score: 20, comment: 'poor' },
                { score: 27, comment: 'poor' },
                { score: 76, comment: 'distinction' },
                { score: 36, comment: 'poor' },
                { score: 71, comment: 'pass' },
            ],
        },
    ],
    options: {
        type: 'unsorted array',
    },
};
