module.exports = {
    testcases: [
        {
            input: [['Reward', 'Nil', 'Reward', 'Reward', 'Nil', 'Reward', 'Reward', 'Reward', 'Nil', 'Nil']],
            expected: 11,
        },
        {
            input: [['Reward', 'Nil', 'Nil', 'Reward', 'Reward', 'Reward', 'Nil', 'Reward', 'Reward', 'Reward']],
            expected: 17,
        },
        {
            input: [['Nil', 'Reward', 'Reward', 'Reward', 'Nil', 'Nil', 'Nil', 'Nil', 'Nil']],
            expected: 0,
        },
        {
            input: [['Reward']],
            expected: 1,
        },
        {
            input: [['Reward', 'Reward', 'Reward']],
            expected: 8,
        },
        {
            input: [['Reward', 'Reward', 'Nil', 'Reward']],
            expected: 3,
        },
        {
            input: [['Reward', 'Reward', 'Nil', 'Reward', 'Nil', 'Reward', 'Reward', 'Reward']],
            expected: 11,
        },
        {
            input: [['Nil']],
            expected: 0,
        },
        {
            input: [['Nil', 'Nil', 'Nil']],
            expected: 0,
        },
        {
            input: [['Nil', 'Nil', 'Nil', 'Reward']],
            expected: 1,
        },
        {
            input: [['Nil', 'Nil', 'Nil', 'Reward', 'Reward', 'Reward']],
            expected: 8,
        },
        {
            input: [['Nil', 'Nil', 'Nil', 'Reward', 'Reward', 'Reward', 'Nil', 'Reward']],
            expected: 9,
        },
        {
            input: [['Nil', 'Nil', 'Nil', 'Reward', 'Reward', 'Reward', 'Nil', 'Reward', 'Reward', 'Reward']],
            expected: 16,
        },
        {
            input: [[]],
            expected: 0,
        },
        {
            input: [['Reward', 'Nil', 'Nil', 'Reward', 'Nil', 'Nil', 'Nil', 'Nil', 'Reward', 'Nil']],
            expected: 3,
        },
        {
            input: [['Reward', 'Nil', 'Nil', 'Nil', 'Nil', 'Nil', 'Nil', 'Nil', 'Reward', 'Nil']],
            expected: 0,
        },
        {
            input: [
                [
                    'Nil',
                    'Nil',
                    'Reward',
                    'Nil',
                    'Nil',
                    'Nil',
                    'Reward',
                    'Nil',
                    'Nil',
                    'Nil',
                    'Reward',
                    'Reward',
                    'Nil',
                    'Nil',
                    'Nil',
                ],
            ],
            expected: 4,
        },
        {
            input: [
                [
                    'Reward',
                    'Reward',
                    'Nil',
                    'Nil',
                    'Reward',
                    'Nil',
                    'Reward',
                    'Reward',
                    'Nil',
                    'Nil',
                    'Nil',
                    'Nil',
                    'Reward',
                    'Nil',
                    'Nil',
                    'Nil',
                    'Nil',
                    'Reward',
                    'Nil',
                    'Nil',
                    'Reward',
                    'Reward',
                    'Reward',
                    'Nil',
                    'Reward',
                    'Nil',
                    'Reward',
                    'Nil',
                    'Reward',
                    'Reward',
                ],
            ],
            expected: 19,
        },
        {
            input: [
                [
                    'Nil',
                    'Nil',
                    'Reward',
                    'Reward',
                    'Reward',
                    'Nil',
                    'Nil',
                    'Nil',
                    'Nil',
                    'Nil',
                    'Nil',
                    'Reward',
                    'Nil',
                    'Nil',
                    'Nil',
                    'Nil',
                    'Reward',
                    'Nil',
                    'Nil',
                    'Reward',
                    'Reward',
                    'Reward',
                    'Nil',
                    'Nil',
                    'Reward',
                    'Reward',
                    'Nil',
                    'Nil',
                    'Nil',
                    'Nil',
                    'Nil',
                    'Nil',
                    'Nil',
                    'Nil',
                    'Nil',
                    'Nil',
                    'Nil',
                    'Nil',
                    'Reward',
                    'Nil',
                    'Reward',
                    'Nil',
                    'Reward',
                    'Nil',
                    'Reward',
                    'Reward',
                    'Reward',
                    'Nil',
                    'Nil',
                    'Reward',
                ],
            ],
            expected: 0,
        },
        {
            input: [
                [
                    'Nil',
                    'Nil',
                    'Reward',
                    'Reward',
                    'Reward',
                    'Nil',
                    'Nil',
                    'Reward',
                    'Nil',
                    'Reward',
                    'Nil',
                    'Reward',
                    'Nil',
                    'Nil',
                    'Nil',
                    'Reward',
                    'Reward',
                    'Nil',
                    'Nil',
                    'Reward',
                    'Reward',
                    'Reward',
                    'Nil',
                    'Nil',
                    'Reward',
                    'Reward',
                    'Nil',
                    'Nil',
                    'Reward',
                    'Reward',
                    'Nil',
                    'Reward',
                    'Reward',
                    'Nil',
                    'Nil',
                    'Reward',
                    'Reward',
                    'Nil',
                    'Reward',
                    'Nil',
                    'Reward',
                    'Nil',
                    'Reward',
                    'Nil',
                    'Reward',
                    'Reward',
                    'Reward',
                    'Nil',
                    'Nil',
                    'Reward',
                ],
            ],
            expected: 41,
        },
    ],
    options: {
        type: 'JSON',
    },
};
