module.exports = {
    testcases: [
        {
            input: [
                [
                    { name: 'raspberry', weight: 10 },
                    { name: 'blueberry', weight: 14 },
                ],
                18,
            ],
            expected: { name: 'blueberry', weight: 14 },
        },
        {
            input: [
                [
                    { name: 'apple', weight: 200 },
                    { name: 'grape', weight: 600 },
                    { name: 'orange', weight: 350 },
                ],
                500,
            ],
            expected: { name: 'grape', weight: 600 },
        },
        {
            input: [
                [
                    { name: 'apple', weight: 200 },
                    { name: 'orange', weight: 350 },
                ],
                350,
            ],
            expected: { name: 'orange', weight: 350 },
        },
        {
            input: [
                [
                    { name: 'Olive', weight: 368 },
                    { name: 'Honeydew', weight: 153 },
                    { name: 'Tomato', weight: 149 },
                    { name: 'Apple', weight: 129 },
                    { name: 'Starfruit', weight: 232 },
                    { name: 'Fig', weight: 191 },
                    { name: 'Cherry', weight: 103 },
                    { name: 'Yuzu', weight: 377 },
                    { name: 'Watermelon', weight: 219 },
                    { name: 'Quince', weight: 203 },
                ],
                346,
            ],
            expected: { name: 'Olive', weight: 368 },
        },
        {
            input: [
                [
                    { name: 'Kiwi', weight: 295 },
                    { name: 'Peach', weight: 368 },
                    { name: 'Quince', weight: 153 },
                    { name: 'Mango', weight: 379 },
                    { name: 'Yuzu', weight: 396 },
                    { name: 'Starfruit', weight: 318 },
                    { name: 'Date', weight: 154 },
                    { name: 'Olive', weight: 357 },
                    { name: 'Watermelon', weight: 394 },
                    { name: 'Honeydew', weight: 250 },
                ],
                242,
            ],
            expected: { name: 'Honeydew', weight: 250 },
        },
        {
            input: [
                [
                    { name: 'Quince', weight: 303 },
                    { name: 'Elderberry', weight: 108 },
                    { name: 'Rambutan', weight: 244 },
                    { name: 'Kiwi', weight: 361 },
                    { name: 'Fig', weight: 178 },
                    { name: 'Starfruit', weight: 273 },
                    { name: 'Yuzu', weight: 316 },
                    { name: 'Mango', weight: 155 },
                    { name: 'Jackfruit', weight: 181 },
                    { name: 'Tomato', weight: 388 },
                ],
                305,
            ],
            expected: { name: 'Quince', weight: 303 },
        },
        {
            input: [
                [
                    { name: 'Elderberry', weight: 220 },
                    { name: 'Cherry', weight: 367 },
                    { name: 'Apple', weight: 361 },
                    { name: 'Jackfruit', weight: 296 },
                    { name: 'Date', weight: 254 },
                    { name: 'Starfruit', weight: 114 },
                    { name: 'Peach', weight: 118 },
                    { name: 'Yuzu', weight: 354 },
                    { name: 'Fig', weight: 228 },
                    { name: 'Quince', weight: 189 },
                ],
                144,
            ],
            expected: { name: 'Peach', weight: 118 },
        },
        {
            input: [
                [
                    { name: 'Lime', weight: 166 },
                    { name: 'Rambutan', weight: 337 },
                    { name: 'Apple', weight: 359 },
                    { name: 'Watermelon', weight: 292 },
                    { name: 'Elderberry', weight: 304 },
                    { name: 'Nectarine', weight: 350 },
                    { name: 'Mango', weight: 325 },
                    { name: 'Cherry', weight: 253 },
                    { name: 'Jackfruit', weight: 243 },
                    { name: 'Tomato', weight: 142 },
                ],
                192,
            ],
            expected: { name: 'Lime', weight: 166 },
        },
        {
            input: [
                [
                    { name: 'Date', weight: 151 },
                    { name: 'Grape', weight: 328 },
                    { name: 'Apple', weight: 102 },
                    { name: 'Quince', weight: 176 },
                    { name: 'Nectarine', weight: 384 },
                    { name: 'Lime', weight: 146 },
                    { name: 'Peach', weight: 232 },
                    { name: 'Cherry', weight: 333 },
                    { name: 'Mango', weight: 244 },
                    { name: 'Elderberry', weight: 219 },
                ],
                294,
            ],
            expected: { name: 'Grape', weight: 328 },
        },
        {
            input: [
                [
                    { name: 'Mango', weight: 184 },
                    { name: 'Peach', weight: 243 },
                    { name: 'Grape', weight: 102 },
                    { name: 'Jackfruit', weight: 281 },
                    { name: 'Olive', weight: 355 },
                    { name: 'Elderberry', weight: 348 },
                    { name: 'Apple', weight: 173 },
                    { name: 'Honeydew', weight: 175 },
                    { name: 'Yuzu', weight: 276 },
                    { name: 'Rambutan', weight: 136 },
                ],
                126,
            ],
            expected: { name: 'Rambutan', weight: 136 },
        },
        {
            input: [
                [
                    { name: 'Starfruit', weight: 317 },
                    { name: 'Tomato', weight: 230 },
                    { name: 'Quince', weight: 391 },
                    { name: 'Fig', weight: 278 },
                    { name: 'Olive', weight: 350 },
                    { name: 'Yuzu', weight: 237 },
                    { name: 'Mango', weight: 256 },
                    { name: 'Cherry', weight: 114 },
                    { name: 'Banana', weight: 308 },
                    { name: 'Kiwi', weight: 294 },
                ],
                308,
            ],
            expected: { name: 'Banana', weight: 308 },
        },
        {
            input: [
                [
                    { name: 'Lime', weight: 272 },
                    { name: 'Watermelon', weight: 170 },
                    { name: 'Honeydew', weight: 166 },
                    { name: 'Yuzu', weight: 322 },
                    { name: 'Quince', weight: 296 },
                    { name: 'Rambutan', weight: 380 },
                    { name: 'Grape', weight: 284 },
                    { name: 'Nectarine', weight: 167 },
                    { name: 'Cherry', weight: 377 },
                    { name: 'Tomato', weight: 295 },
                ],
                198,
            ],
            expected: { name: 'Watermelon', weight: 170 },
        },
        {
            input: [
                [
                    { name: 'Yuzu', weight: 333 },
                    { name: 'Tomato', weight: 278 },
                    { name: 'Quince', weight: 282 },
                    { name: 'Nectarine', weight: 280 },
                    { name: 'Apple', weight: 161 },
                    { name: 'Jackfruit', weight: 362 },
                    { name: 'Honeydew', weight: 166 },
                    { name: 'Elderberry', weight: 165 },
                    { name: 'Banana', weight: 144 },
                    { name: 'Starfruit', weight: 116 },
                ],
                225,
            ],
            expected: { name: 'Tomato', weight: 278 },
        },
        {
            input: [
                [
                    { name: 'Mango', weight: 300 },
                    { name: 'Honeydew', weight: 243 },
                    { name: 'Watermelon', weight: 113 },
                    { name: 'Yuzu', weight: 340 },
                    { name: 'Kiwi', weight: 316 },
                    { name: 'Cherry', weight: 182 },
                    { name: 'Jackfruit', weight: 269 },
                    { name: 'Quince', weight: 115 },
                    { name: 'Tomato', weight: 146 },
                    { name: 'Grape', weight: 221 },
                    { name: 'Peach', weight: 114 },
                    { name: 'Lime', weight: 361 },
                    { name: 'Fig', weight: 248 },
                    { name: 'Starfruit', weight: 306 },
                    { name: 'Date', weight: 381 },
                    { name: 'Banana', weight: 250 },
                    { name: 'Apple', weight: 331 },
                    { name: 'Olive', weight: 166 },
                    { name: 'Rambutan', weight: 369 },
                    { name: 'Nectarine', weight: 127 },
                ],
                160,
            ],
            expected: { name: 'Olive', weight: 166 },
        },
        {
            input: [
                [
                    { name: 'Grape', weight: 107 },
                    { name: 'Lime', weight: 292 },
                    { name: 'Mango', weight: 255 },
                    { name: 'Banana', weight: 208 },
                    { name: 'Jackfruit', weight: 386 },
                    { name: 'Nectarine', weight: 150 },
                    { name: 'Date', weight: 106 },
                    { name: 'Elderberry', weight: 200 },
                    { name: 'Peach', weight: 250 },
                    { name: 'Olive', weight: 235 },
                    { name: 'Rambutan', weight: 298 },
                    { name: 'Quince', weight: 387 },
                    { name: 'Cherry', weight: 285 },
                    { name: 'Kiwi', weight: 398 },
                    { name: 'Yuzu', weight: 171 },
                    { name: 'Fig', weight: 293 },
                    { name: 'Apple', weight: 226 },
                    { name: 'Tomato', weight: 105 },
                    { name: 'Watermelon', weight: 270 },
                    { name: 'Honeydew', weight: 192 },
                ],
                234,
            ],
            expected: { name: 'Olive', weight: 235 },
        },
        {
            input: [
                [
                    { name: 'Tomato', weight: 384 },
                    { name: 'Yuzu', weight: 190 },
                    { name: 'Watermelon', weight: 331 },
                    { name: 'Apple', weight: 239 },
                    { name: 'Date', weight: 265 },
                    { name: 'Olive', weight: 396 },
                    { name: 'Peach', weight: 122 },
                    { name: 'Banana', weight: 352 },
                    { name: 'Starfruit', weight: 398 },
                    { name: 'Jackfruit', weight: 254 },
                    { name: 'Quince', weight: 111 },
                    { name: 'Honeydew', weight: 388 },
                    { name: 'Fig', weight: 165 },
                    { name: 'Mango', weight: 280 },
                    { name: 'Lime', weight: 341 },
                    { name: 'Kiwi', weight: 233 },
                    { name: 'Elderberry', weight: 305 },
                    { name: 'Grape', weight: 361 },
                    { name: 'Cherry', weight: 161 },
                    { name: 'Nectarine', weight: 228 },
                ],
                343,
            ],
            expected: { name: 'Lime', weight: 341 },
        },
        {
            input: [
                [
                    { name: 'Grape', weight: 132 },
                    { name: 'Cherry', weight: 193 },
                    { name: 'Nectarine', weight: 205 },
                    { name: 'Kiwi', weight: 104 },
                    { name: 'Olive', weight: 130 },
                    { name: 'Tomato', weight: 359 },
                    { name: 'Apple', weight: 160 },
                    { name: 'Starfruit', weight: 190 },
                    { name: 'Honeydew', weight: 117 },
                    { name: 'Elderberry', weight: 202 },
                    { name: 'Mango', weight: 282 },
                    { name: 'Date', weight: 127 },
                    { name: 'Watermelon', weight: 192 },
                    { name: 'Rambutan', weight: 237 },
                    { name: 'Banana', weight: 175 },
                    { name: 'Fig', weight: 264 },
                    { name: 'Jackfruit', weight: 112 },
                    { name: 'Lime', weight: 286 },
                    { name: 'Quince', weight: 148 },
                    { name: 'Peach', weight: 331 },
                ],
                259,
            ],
            expected: { name: 'Fig', weight: 264 },
        },
        {
            input: [
                [
                    { name: 'Starfruit', weight: 249 },
                    { name: 'Fig', weight: 148 },
                    { name: 'Lime', weight: 112 },
                    { name: 'Rambutan', weight: 385 },
                    { name: 'Cherry', weight: 279 },
                    { name: 'Date', weight: 139 },
                    { name: 'Peach', weight: 155 },
                    { name: 'Yuzu', weight: 106 },
                    { name: 'Grape', weight: 178 },
                    { name: 'Honeydew', weight: 242 },
                    { name: 'Elderberry', weight: 221 },
                    { name: 'Quince', weight: 137 },
                    { name: 'Apple', weight: 238 },
                    { name: 'Jackfruit', weight: 115 },
                    { name: 'Olive', weight: 185 },
                    { name: 'Watermelon', weight: 371 },
                    { name: 'Banana', weight: 154 },
                    { name: 'Nectarine', weight: 264 },
                    { name: 'Tomato', weight: 372 },
                    { name: 'Mango', weight: 142 },
                ],
                248,
            ],
            expected: { name: 'Starfruit', weight: 249 },
        },
        {
            input: [
                [
                    { name: 'Date', weight: 284 },
                    { name: 'Grape', weight: 260 },
                    { name: 'Watermelon', weight: 336 },
                    { name: 'Rambutan', weight: 394 },
                    { name: 'Banana', weight: 308 },
                    { name: 'Yuzu', weight: 344 },
                    { name: 'Kiwi', weight: 225 },
                    { name: 'Cherry', weight: 145 },
                    { name: 'Peach', weight: 250 },
                    { name: 'Honeydew', weight: 201 },
                    { name: 'Quince', weight: 191 },
                    { name: 'Starfruit', weight: 317 },
                    { name: 'Elderberry', weight: 105 },
                    { name: 'Apple', weight: 391 },
                    { name: 'Nectarine', weight: 238 },
                    { name: 'Fig', weight: 167 },
                    { name: 'Tomato', weight: 163 },
                    { name: 'Mango', weight: 218 },
                    { name: 'Lime', weight: 222 },
                    { name: 'Olive', weight: 310 },
                ],
                237,
            ],
            expected: { name: 'Nectarine', weight: 238 },
        },
        {
            input: [
                [
                    { name: 'Kiwi', weight: 260 },
                    { name: 'Apple', weight: 222 },
                    { name: 'Nectarine', weight: 213 },
                    { name: 'Starfruit', weight: 115 },
                    { name: 'Date', weight: 101 },
                    { name: 'Honeydew', weight: 196 },
                    { name: 'Watermelon', weight: 280 },
                    { name: 'Tomato', weight: 275 },
                    { name: 'Banana', weight: 329 },
                    { name: 'Yuzu', weight: 179 },
                    { name: 'Cherry', weight: 283 },
                    { name: 'Quince', weight: 299 },
                    { name: 'Peach', weight: 147 },
                    { name: 'Lime', weight: 355 },
                    { name: 'Jackfruit', weight: 221 },
                    { name: 'Elderberry', weight: 330 },
                    { name: 'Fig', weight: 133 },
                    { name: 'Grape', weight: 162 },
                    { name: 'Olive', weight: 228 },
                    { name: 'Mango', weight: 302 },
                ],
                253,
            ],
            expected: { name: 'Kiwi', weight: 260 },
        },
    ],
    options: {
        type: 'JSON',
    },
};
